# Generated by Django 4.2.3 on 2023-07-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='located',
            new_name='city',
        ),
    ]
