# Generated by Django 4.2.3 on 2023-07-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_located_testimonial_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='content',
            new_name='text',
        ),
    ]
