# Generated by Django 4.2.3 on 2023-09-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='city',
        ),
    ]
