# Generated by Django 4.2.3 on 2023-09-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_testimonial_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='comment',
        ),
    ]
